MEMORY_LIMIT = 1.0

PER_DEVICE_BATCH_SIZE = 16
LEARNING_RATE = 2e-5
MAX_N_EPOCHS = 10

TRAIN_DATA_SIZE = 1000
VALID_DATA_SIZE = 200
TEST_DATA_SIZE = 200


MLFLOW_TRACKING_URI = "http://localhost:5001"
MLFLOW_EXPERIMENT_ID = "resnet152"
MLFLOW_RUN_NAME = "fspd"
